### ISSUE TITLE
Editing in the frontend view does not work

### ISSUE THREAD

**Issue by tyndouf** [swatty007/laravel-inline-editor#1]
Hi, 

The content I put between of my @inlineEditor and @endinlineEditor tags is saved in my database, but I can't edit the content in the frontend of my page.

Any idea what I can do to solve this problem?

In advance , thank you.

**Comment by izdrail** [comment]
did you try to see if you get any errors with vuejs dev tools? I had some issues as well at the beginning but I've managed to make it work, 
In my case, I was putting the HTML block outside of the app

**Comment by tyndouf** [comment]
Thank you, I'll give it a try again and let you know if I notice any error message
