### ISSUE TITLE
iPhone / iPad support.

### ISSUE THREAD

**Issue by rushadaev** [swatty007/laravel-inline-editor#2]
Trouble using this editor with iPhone or iPad.
These devices use their own inline editor features(but only B, I, U). 
It is good designed and works well(Thanks Apple), but can we expand this default Apple devices functionality? Add at least alignment functions and headers?

To reproduce this issue, just open any of your project on iPhone or iPad.

**Comment by swatty007** [comment]
The actuall inline functionallity is the front end part, that comes from the medium library. You can control its options by supplying it the corresponding config options like described in the readme under usage:
https://github.com/swatty007/laravel-inline-editor#usage
You can find the possible options here:
https://github.com/yabwe/medium-editor#all-buttons
so for example .. , 'toolbar': { 'buttons': ['bold', 'italic', 'underline', 'h1', 'h2', 'justifyFull', 'justifyLeft' ... ] } }
Tough thats obvisously not extending any default iOS ui.
